
# NUMPY

## Numpy is a general purpose array-processing package in python

In [1]:
import numpy as np


In [2]:
#1d array from a python list
arr1d=np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [3]:
#2d array from a nested python list
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array attributes

In [ ]:
#shape
shape=arr2d.shape
shape

(2, 3)

In [ ]:
zeros_arr.shape

(3, 4)

In [ ]:
size=arr2d.size
size

6

In [ ]:
zeros_arr.size

12

In [ ]:
#data type
data_type=arr2d.dtype
data_type

dtype('int64')

In [ ]:
zeros_arr.dtype

dtype('float64')

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## Array Operations

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#addition
addition=2+ arr2d
print(addition)

[[3 4 5]
 [6 7 8]]


In [ ]:
#substraction
substraction=arr2d - 3
print(substraction)

[[-2 -1  0]
 [ 1  2  3]]


In [ ]:
#Multiplication
Multiplication=4*arr2d
print(Multiplication)


[[ 4  8 12]
 [16 20 24]]


## Aggregation Functions

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#sum
total_sum=arr2d.sum()
print(total_sum)

21


In [ ]:
#max
max_val=arr2d.max()
print(max_val)

6


In [ ]:
#min
min_val=arr2d.min()
print(min_val)

1


## Indexing

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#second row
second_row=arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [ ]:
second_row_element=arr2d[1:,1:]
print(second_row_element)

[[5 6]]


In [ ]:
first_row_element=arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [ ]:
first_row=arr2d[0,1:]
print(first_row)

[2 3]


In [ ]:
first_row_=arr2d[:1,1:]
print(first_row_)

[[2 3]]


## Array Manipulation

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2d.shape

(2, 3)

In [ ]:
#Reshape
reshape_arr=arr2d.reshape(3,2)
print(reshape_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
reshape_arr1=arr2d.reshape(1,6)
print(reshape_arr1)

[[1 2 3 4 5 6]]


In [ ]:
#concatenate Arrays
arr1d=[1,2,3]
concat_arr=np.concat([arr1d,arr1d])
print(concat_arr)

[1 2 3 1 2 3]


In [ ]:
#concatenate Arrays 2
arr1d=np.array([1,2,3])
concat_arr2=np.concatenate([arr1d,np.array([4,5,6])])
print(concat_arr2)

[1 2 3 4 5 6]


In [ ]:
arr1d=np.array([1,2,3])
append_arr=np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])
append_arr1=np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Question asked

### Can you append a row ([4,5,6]) to the array [1,2,3], so it looks like this [[1,2,3],[4,5,6]] rather than this: [1,2,3,4,5,6]?

### Answer: To achieve that, both arrays need to be two-dimensional arrays.

In [ ]:
#Answer to question asked
arr1d=np.array([[1,2,3]])
concat_arr2=np.concatenate([arr1d,np.array([[4,5,6]])])
print(concat_arr2)

[[1 2 3]
 [4 5 6]]


## Broadcasting

In [ ]:
#broadcasting
a=np.array([1,2,3])
b=4
print(a+b)

[5 6 7]


In [ ]:
a=np.array([1,2,3])
b=6
print(a*b)

[ 6 12 18]


In [ ]:
a=np.array([1,2,3])
print(4+a)

[5 6 7]


## Random Number Generation


In [ ]:
random_numbers=np.random.rand(3,3)
print(random_numbers)

[[0.88580173 0.91017469 0.13070437]
 [0.24210686 0.44703756 0.84304427]
 [0.80179439 0.47905931 0.55817974]]


In [ ]:
random_numbers=np.random.rand(4,6)
print(random_numbers)

[[2.88965679e-01 6.08474220e-01 7.86302281e-01 2.37557658e-01
  7.38451753e-01 9.99427971e-01]
 [8.73707282e-01 7.77683945e-01 9.72943992e-02 1.11042670e-01
  5.56833207e-01 3.89032119e-01]
 [6.63064854e-01 1.90781238e-02 3.23627129e-04 8.73761670e-01
  2.21563765e-01 4.25419958e-01]
 [3.78030924e-02 7.12734149e-01 7.19722955e-03 1.06639448e-01
  7.00080896e-01 1.65969318e-01]]


In [ ]:
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[47 31 19 87 29 51]


In [ ]:
random_numbers_ = np.random.randint(0,100,6).reshape(3,2)
print(random_numbers_)

[[67 82]
 [10 61]
 [28 31]]


In [ ]:
random_numbers1=np.random.rand(4,7)
print(random_numbers1)

[[0.65057475 0.53774477 0.10091799 0.93296265 0.59730496 0.26237141
  0.73265792]
 [0.2837599  0.81968454 0.51310408 0.54475515 0.05383892 0.14238752
  0.58365612]
 [0.53246418 0.80206227 0.14635574 0.985103   0.70609377 0.8990799
  0.11678072]
 [0.54769963 0.23062762 0.02159128 0.44221449 0.37831518 0.44273862
  0.72792059]]


In [ ]:
item=np.array(['A','B','C','D'])
item

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [ ]:
random_numbers2=np.random.choice(item,3)
print(random_numbers2)

['C' 'D' 'B']


## Linear Algebra

In [ ]:
#matrix addition
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
print(A+B)

[[ 6  8]
 [10 12]]


In [ ]:
print(A-B)

[[-4 -4]
 [-4 -4]]


In [ ]:
print(A*B)

[[ 5 12]
 [21 32]]


In [ ]:
#Matrix Multiplication
print(A@B)

[[19 22]
 [43 50]]


In [ ]:
result=np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
#Normal Matrix Multiplication
f=np.dot(A,B)
print(f)

[[19 22]
 [43 50]]


In [ ]:
#Matrix Multiplication (Column-wise)
print(A*B)

[[ 5 12]
 [21 32]]


In [ ]:
# Standard Matrix multiplication
f=np.dot(A,B)
f

array([[19, 22],
       [43, 50]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
##Transpose of a matrix
transpose_A=np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [ ]:
#Transpose of a matrix
transpose_B=np.transpose(B)
print(transpose_B)

[[5 7]
 [6 8]]


In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B_inv=np.linalg.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [ ]:
#identity Matrix
identity_marix=np.eye(4)
print(identity_marix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
##determinant of a matrix
determinant=np.linalg.det(B)
print(int(determinant))

-2


## Delete elements in an array


In [ ]:
arr=np.array([1,2,3,4,5])
arr_deleted=np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [ ]:
arr_deleted = np.delete(arr,4)
print(arr_deleted)

[1 2 3 4]


In [ ]:
club_arr=np.array(['Madrid','Barcelona','Arsenal','Dortmund','Mancity'])
arr_deleted=np.delete(club_arr,[1,2])
print(arr_deleted)

['Madrid' 'Dortmund' 'Mancity']


In [ ]:
arr=np.array([1,2,3,4,5])
m=arr!=5
new_arr=arr[m]
print(new_arr)

[1 2 3 4]


### To make sure that the elements that are removed in arr_deleted are also deleted in club_arr

In [ ]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
club_arr = arr_deleted
print(club_arr)


['Madrid' 'Dortmund' 'PSG' 'Mancity']






## Statistical Functions

In [ ]:
arr=np.array([1,2,3,4,5])


In [ ]:
#mean
arr_mean=np.mean(arr)
print(arr_mean)

3.0


In [ ]:
#median
arr_median=np.median(arr)
print(arr_median)

3.0


In [ ]:
arr_1 = np.array([1,2,3,4,5,6])

In [ ]:
arr1_median = np.median(arr_1)
print(arr1_median)

3.5


In [7]:
#Mode : numpy does not have the mode method, so scipy can be used
arr_=np.array([1,2,3,4,5,6])
from scipy import stats
arr_mode =stats.mode(arr_,keepdims=False)
print(arr_mode)

ModeResult(mode=np.int64(1), count=np.int64(1))


In [9]:
#standard deviation
arr_std=np.std(arr_)
print(arr_std)

1.707825127659933
